-- Initial schema for juniemvc: Beer, BeerOrder, BeerOrderLine

-- Table: beer
CREATE TABLE beer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_name VARCHAR(255),
    beer_style VARCHAR(255),
    upc VARCHAR(255),
    quantity_on_hand INTEGER,
    price DECIMAL(19,2),
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Table: beer_order
CREATE TABLE beer_order (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    customer_ref VARCHAR(255),
    payment_amount DECIMAL(19,2),
    status VARCHAR(50),
    created_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Table: beer_order_line
CREATE TABLE beer_order_line (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_order_id INTEGER NOT NULL,
    beer_id INTEGER NOT NULL,
    order_quantity INTEGER,
    quantity_allocated INTEGER,
    status VARCHAR(50),
    created_date TIMESTAMP,
    update_date TIMESTAMP,
    CONSTRAINT fk_bol_order FOREIGN KEY (beer_order_id) REFERENCES beer_order (id) ON DELETE CASCADE,
    CONSTRAINT fk_bol_beer FOREIGN KEY (beer_id) REFERENCES beer (id)
);

-- Helpful indexes for FK lookups
CREATE INDEX idx_bol_order ON beer_order_line (beer_order_id);
CREATE INDEX idx_bol_beer ON beer_order_line (beer_id);
